# Assignment

## Q1. WAP which will find all such numbers which are divisible by 7 but are not a multiple of 5 between 2000 and 3200 both included.

In [7]:
div7=[]
div35=[]
for i in range(2000,3201):
    if i%7==0:
        div7.append(i)
    if i%35==0:
        div35.append(i)
result= set(div7) - set(div35)
result=list(sorted(result))
print(result)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


## Q2. WAP to generate a dictionary that contains (i,i*i) as key value pair from 1 to the given input 'n'.

In [10]:
n=int(input("Enter the value of n: "))
dictionary = {i:i*i for i in range(1,n+1)}
print(dictionary)

Enter the value of n: 5
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


## Q3. WAP which takes two digits x,y as inputs and generate a 2-D array. The element value in the i th row and j th column should be i*j. 

In [22]:
try:
    [x,y]=[int(i) for i in input("Enter the values of x and y: ").split()]   
except Exception:
    print("You did not enter exactly 2 numbers. Aborting!!") 

arr=[ [] for _ in range(x) ]

for i in range(x):
    for j in range(y):
        arr[i].append(i*j)

import numpy as np

print(np.array(arr))

Enter the values of x and y: 5 6
[[ 0  0  0  0  0  0]
 [ 0  1  2  3  4  5]
 [ 0  2  4  6  8 10]
 [ 0  3  6  9 12 15]
 [ 0  4  8 12 16 20]]


## Q4. WAP that computes the net amount of a bank account based on the transaction log from console input.

In [7]:
tLog=[int(i) for i in input("Enter transaction logs ((+)number for credit and (-)number for debit): ").split()]
net=0  # Initial bank balance is assumed to be 0.
flag=0
try:
    for i in range(len(tLog)):
        net+=tLog[i]
        if net < 0:
            raise Exception
except Exception:
    print("Transaction log is unrealistic, bank can't have a negative net amount. Aborting!!")
    flag=1
    
if flag==0:   
    print("\nNet amount of bank account is {}".format(net))

Enter transaction logs ((+)number for credit and (-)number for debit): 1 2 3 4 

Net amount of bank account is 10


## Q5. A website requires the users to input username and password to register themselves. WAP to check the validity of the password input by user. Following are the criteria for checking the password:-

### 1. Atleast 1 lower alphabet [a-z]
### 2. Atleast 1 digit [0-9]
### 3. Atleast 1 upper alphabet [A-Z]
### 4. Atlease one of the symbol from set [$,#,@] 


### Minimum and maximum length of the password must be 6 and 12 resp.

In [10]:
import re

def checkPassword(password):
    '''
    This function checks the password for following criterias:
        1. Must contain atleast 1 lower alphabet [a-z]
        2. Must contain atleast 1 digit [0-9]
        3. Must contain atleast 1 upper alphabet [A-Z]
        4. Must contain atleast one of the symbol in [$,#,@] and no other symbols are allowed.
        5. Minimum and maximum length of the password must be 6 and 12 resp.
    '''
    checkSymbol = re.compile('[$#@]')
    checkDigit = re.compile('[1-9]')
    checkUpper = re.compile('[A-Z]')
    checkLower = re.compile('[a-z]')

    flag=0
    # flag=0 means password is fine
    # flag=1 means password does not satisfy the length criteria
    # flag=2 means password doesn't contain atleast 1 lower letter, 1 upper letter, 1 digit and 1 special characters from the set {$,#,@}

    if len(password)<6 or len(password)>12:
        flag=1
    if flag==0 and (checkSymbol.search(password)== None or checkDigit.search(password)==None):
        flag=2 
    if flag==0 and (checkUpper.search(password)==None or checkLower.search(password)==None):    
        flag=2
    
    if flag==0:
        for i in password:
            if i.isalnum()==True:
                pass
            elif checkSymbol.search(i)==None:
                flag=2
                break
            
    return flag   


username=input("Enter Username: ")
password=input("Enter Password: ")

flag=checkPassword(password)

if flag==1:
    print("Could not register!! Either password is too long or too short.")
elif flag==2:
    print("Could not register!! The password must contain atleast 1 lower letter, 1 upper letter, 1 digit and 1 special character from the set {$,#,@}.")
else:
    print("Successfully registered.")

Enter Username: sdf
Enter Password: sdfasd@A3
Successfully registered.
